format = """\
$env_var$username${custom.username_root}$hostname\
[](bg:#00000000 fg:#8caaee)\
[${directory} ](bg:#8caaee fg:#ffffff)\
${custom.git} \
"""

[directory]
format = "\uf114 $path($style)"
style = "fg:#c6d0f5 bg:#8caaee"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = " "
style = "fg:#1C3A5E bg:#e5c890"

[custom.git]
command = "~/.config/starship/custom.git.sh || true"
when = "true"
format = "$output"
