# Reuses the same lockscreen.png the Sway session used.
background {
    monitor =
    path = $HOME/.config/hypr/lockscreen.png
    blur_passes = 0
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_center = true
    outer_color = rgb(a6d189)
    inner_color = rgb(232634)
    font_color = rgb(babbf1)
    fail_color = rgb(e78284)
    placeholder_text = <i>Password…</i>
    fade_on_empty = false
}
