general {
    lock_cmd = pidof hyprlock || hyprlock       # avoids running multiple instances
    before_sleep_cmd = loginctl lock-session    # tells systemd to trigger lock before sleeping
}

# (Optional) This listener block is only for IDLE timeouts when you step away
listener {
    timeout = 300                               # 5 minutes
    on-timeout = loginctl lock-session          # lock screen if idle
    on-status-change = if [ "$1" = "sleep" ]; then hyprlock; fi
}
